workflows:
  android-release:
    name: Strive Android Release
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter create .
      - sed -i 's/minSdkVersion 21/minSdkVersion 23/' android/app/build.gradle
      - sed -i 's/applicationId "com.example.strive"/applicationId "com.strive.gym"/' android/app/build.gradle
      - flutter pub get
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
